### ISSUE TITLE
Window not aligned with taskbar and misaligned to the left

### ISSUE THREAD

**Issue by leopucci** [pixtron/electron-traywindow-positioner#20]
Hey there! Thanks for taking some time to create this module. 
I am having trouble aligning the BrowserWindow on the screen for some reason. 
The S.O. is windows, I am using one monitor to test it. 
The window is placed to the left instead of the right side of the screen, 
Also there is a gap between the bottom of the window and the tray bar. 
Could you help me use your module properly? Maybe I am doing something wrong. 
I am using just to test on the tray icon click event. 
So I am using tray.getBounds() to get the bounds and using .position(window,traybounds).
What Am I missing?
thanks!
```
tray.on('click', (/* e: any , bounds: any */) => {
    if (mainWindow.isVisible()) {
      mainWindow.hide();
    } else {
      const trayBounds = tray.getBounds();
      electron_traywindow_positioner.position(mainWindow, trayBounds);
}
```
![image](https://user-images.githubusercontent.com/38509299/143682965-260f40f7-49f8-4a4b-a1d4-dab6664d13b8.png)

I was expecting this:
  
![image](https://user-images.githubusercontent.com/38509299/143683246-db5e5961-9cb9-42c4-83f1-62ed78c098ec.png)

**Comment by leopucci** [comment]
Some of the problems solved, after I removed the close/maximize/minimize buttons, now the window is near the task bar.

**Comment by pixtron** [comment]
Sorry for the late reply. First i'd like to say that the positioning of your window is exactly the way this module intends to position windows. 


There are a few [alignment configurations](https://github.com/pixtron/electron-traywindow-positioner#custom-alignment) you might try. But as your window is very wide, the module will always fall back to the positioning you currently experience.

In your case the configuration would be `alignmet.x`:

- `left`: will align the left side of the window to the middle of the tray bounds
- `center`: will align the middle of the window x axis to the middle of the tray bounds
- `right`: will align the right side of the window to the middle of the tray bounds

In case the calculated x position would let the window run out of screen, a [fallback is calculated](https://github.com/pixtron/electron-traywindow-positioner/blob/ab70dc64c1939cbfa78af48b94c931133ce4e3a6/index.js#L119) to make sure the window will fit into screen.

As tray windows usualy are small windows, i suggest you decrease the size of the window. Otherwise if you just want to position the window to the right side of the screen you might overide the `_calculateXAlign` method of this module. It would probably be something like this:


```
 _calculateXAlign(windowBounds, trayBounds, align) {
    const display = this._getDisplay(trayBounds);
    return display.bounds.width + display.bounds.x;
 },
```

But before doing so keep in mind:

- a user might have the taskbar on top, right, bottom or left. 
- on different Operating Systems tray icons might be positioned at another location then on a standard windows setup.
- a user might have multiple montiors to the left, the right, below or above the main display.

Im closing this issue, as i don't think it is a bug. If you feel there is a bug, please open another issue and provide a public github repo where i can reproduce the bug.

**Comment by leopucci** [comment]
Thanks
